### ISSUE TITLE
Please decide on one language to use in issues

### ISSUE THREAD

**Issue by Tommalla** [Soszu/TheChroniclesOfAndaria#4]
Because to trochę jest konfjuzing, nie sądzisz? ;)

**Comment by Tommalla** [comment]
Nie mogłem dodać labela z jakiegoś powodu (GitHub nie pozwolił) :<

**Comment by Soszu** [comment]
Let's do it in english from now on. 

I was tho minded last time + night was late and now you can see the outcome.

What is more my notes are in polish and I was too lazy to translate so i just paste them.
My future input will be in english only.
