### ISSUE TITLE
Showing windows is strangely slow

### ISSUE THREAD

**Issue by Tommalla** [Soszu/TheChroniclesOfAndaria#7]
Wyświetlanie okienek takich jak ekwipunek, bazar, tawerna jest dziwnie wolne - kliknięcie, 1-2s, pojawia się okienko.

uname -a: Linux localhost 3.10.10-gentoo #1 SMP PREEMPT Tue Sep 3 19:45:14 CEST 2013 x86_64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz GenuineIntel GNU/Linux

Qt 4.8.5

**Comment by Soszu** [comment]
I noticed that too, but I have no idea why it happens.

**Comment by Tommalla** [comment]
Does it always happen on your machine or does it happen randomly?

**Comment by Soszu** [comment]
Delay/lag duration seems to be various but it usually occurs.
