### ISSUE TITLE
TICKETS and and phases from DEVELOPMENT POLICY should be added as issues/milestones

### ISSUE THREAD

**Issue by Tommalla** [Soszu/TheChroniclesOfAndaria#8]
I think that [development](https://github.com/Soszu/ZjednoczenieAndarii/wiki/DEVELOPMENT-POLICY) phases/stages should be added to the milestone system, as they are (as mentioned in the text) milestones ;). Under said milestones, there should be issues made of current [TICKETS](https://github.com/Soszu/ZjednoczenieAndarii/wiki/TICKETS) wiki page.

**Comment by Soszu** [comment]
I'll think on adding tickets as issues, thanks for advice!

I already added two phases from development page as milestones and I think that it's enough due to the fact that rest of them is very distant and volatile.
